### ISSUE TITLE
How many network confirmations are needed for StableCoin

### ISSUE THREAD

**Issue by educatedwarrior** [stablecoin/stablecoin#2]
I was curious to know how many confirmations are needed before generated StableCoins could be spent.  Is it 120 confirmations? I didn't see any info about it in the tech specs of the coin.   If you look at transactions details in the wallet this is what you see ..

![image](https://f.cloud.github.com/assets/4054610/1811148/c6853188-6e47-11e3-888c-3c23ff4d35c9.png)

**Comment by stablecoin** [comment]
35 blocks
